# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Optimization Workflow

on: [ push, pull_request ]

jobs:
  common:
    uses: ./.github/workflows/go_ci_common_tasks.yml
  build:
    needs: [common]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: go build -v hi.go
    
